server:
  port: 8086

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
#    password: 1234
    password: 99988776
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=spring30mvc
#  jpa:
#    properties:
#      hibernate:
#        hbm2ddl:
#          auto: create-drop
        
  trymeleaf:
    prefix: classpath:/templates/
  resources:
    static-locations: classpath:/static/
    cache:
      period: 0
#  mvc:
#    view:
#      prefix: /WEB-INF/jsp/
#      suffix: .jsp
logging:
  file:  "logName.log"